"""Bounded, temporary file staging for split-host qualification runs."""

from __future__ import annotations

import hashlib
import re
import secrets
import shlex
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Literal


class RemoteStagingError(RuntimeError):
    """A temporary remote stage could not be created or removed safely."""


_HOST = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,252}")
_REMOTE_ROOT = re.compile(r"/tmp/wspq-[0-9a-f]{24}")


@dataclass(frozen=True)
class StagedFile:
    local: Path
    remote_name: str


def _contains_symlink(path: Path) -> bool:
    current = path.absolute()
    while current != current.parent:
        if current.is_symlink():
            return True
        current = current.parent
    return False


def _identity(path: Path) -> tuple[int, str]:
    return path.stat().st_size, hashlib.sha256(path.read_bytes()).hexdigest()


class RemoteStage:
    """Copy an explicit file set to one fresh remote directory and remove it.

    The target directory is generated by the controller, contains no shell
    metacharacters, and is removed with a fixed Python cleanup program.  The
    class is a context manager so cleanup is attempted on every exit path.
    """

    def __init__(
        self,
        host: str,
        files: tuple[StagedFile, ...],
        *,
        known_hosts: Path,
        remote_python: str,
        remote_python_sha256: str,
        ssh: Path = Path("/usr/bin/ssh"),
        scp: Path = Path("/usr/bin/scp"),
        token: str | None = None,
        owner_token: str | None = None,
        timeout_s: float = 60.0,
    ) -> None:
        if _HOST.fullmatch(host) is None:
            raise RemoteStagingError("remote stage host is invalid")
        if timeout_s <= 0:
            raise RemoteStagingError("remote stage timeout must be positive")
        if (
            re.fullmatch(r"/[A-Za-z0-9._/+:-]+", remote_python) is None
            or re.fullmatch(r"[0-9a-f]{64}", remote_python_sha256) is None
        ):
            raise RemoteStagingError("remote Python identity is invalid")
        stage_token = secrets.token_hex(12) if token is None else token
        self.root = f"/tmp/wspq-{stage_token}"
        if _REMOTE_ROOT.fullmatch(self.root) is None:
            raise RemoteStagingError("remote stage token is invalid")
        self.owner_token = secrets.token_hex(32) if owner_token is None else owner_token
        if re.fullmatch(r"[0-9a-f]{64}", self.owner_token) is None:
            raise RemoteStagingError("remote stage owner token is invalid")
        if not files:
            raise RemoteStagingError("remote stage requires at least one file")
        names: set[str] = set()
        identities: dict[str, tuple[int, str]] = {}
        for item in files:
            if (
                not item.local.is_file()
                or _contains_symlink(item.local)
                or re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", item.remote_name) is None
                or item.remote_name in names
            ):
                raise RemoteStagingError("remote stage file set is invalid")
            names.add(item.remote_name)
            identities[item.remote_name] = _identity(item.local)
        local_bindings = (ssh, scp, known_hosts)
        if any(not path.is_file() or _contains_symlink(path) for path in local_bindings):
            raise RemoteStagingError("remote staging transport identity is unsafe")
        self.host = host
        self.files = files
        self.identities = identities
        self.ssh = ssh
        self.scp = scp
        self.known_hosts = known_hosts
        self.local_transport_identities = {path: _identity(path) for path in local_bindings}
        self.remote_python = remote_python
        self.remote_python_sha256 = remote_python_sha256
        self.timeout_s = timeout_s
        self.cleanup_verified = False

    def _check_transport_identities(self) -> None:
        for path, expected in self.local_transport_identities.items():
            if _contains_symlink(path) or not path.is_file() or _identity(path) != expected:
                raise RemoteStagingError("remote staging transport identity changed")

    def _check_local_identities(self) -> None:
        self._check_transport_identities()
        for item in self.files:
            if (
                _contains_symlink(item.local)
                or not item.local.is_file()
                or _identity(item.local) != self.identities[item.remote_name]
            ):
                raise RemoteStagingError("remote stage source identity changed")

    def _ssh_prefix(self) -> list[str]:
        return [
            str(self.ssh),
            "-o",
            "BatchMode=yes",
            "-o",
            "StrictHostKeyChecking=yes",
            "-o",
            f"UserKnownHostsFile={self.known_hosts}",
            "--",
            self.host,
        ]

    def _scp_prefix(self) -> list[str]:
        return [
            str(self.scp),
            "-q",
            "-o",
            "BatchMode=yes",
            "-o",
            "StrictHostKeyChecking=yes",
            "-o",
            f"UserKnownHostsFile={self.known_hosts}",
            "--",
        ]

    def _python_command(self, program: str, *arguments: str) -> str:
        identity_check = (
            "import hashlib,pathlib,sys;"
            "assert hashlib.sha256(pathlib.Path(sys.executable).read_bytes())"
            f".hexdigest()=='{self.remote_python_sha256}';"
        )
        return shlex.join([self.remote_python, "-c", identity_check + program, *arguments])

    def _run(self, arguments: list[str]) -> subprocess.CompletedProcess[str]:
        try:
            return subprocess.run(
                arguments,
                check=False,
                capture_output=True,
                text=True,
                timeout=self.timeout_s,
                shell=False,
            )
        except (OSError, subprocess.TimeoutExpired) as error:
            raise RemoteStagingError("remote staging transport failed") from error

    def __enter__(self) -> RemoteStage:
        self._check_local_identities()
        remote_command = self._python_command(
            (
                "import os; p=pathlib.Path(sys.argv[1]); os.mkdir(p,0o700);"
                "fd=os.open(p/'.owner',os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o600);"
                "os.write(fd,sys.argv[2].encode('ascii'));os.close(fd)"
            ),
            self.root,
            self.owner_token,
        )
        try:
            mkdir = self._run([*self._ssh_prefix(), remote_command])
            if mkdir.returncode != 0:
                raise RemoteStagingError("remote stage directory creation failed")
            for item in self.files:
                self._check_local_identities()
                copied = self._run(
                    [
                        *self._scp_prefix(),
                        str(item.local),
                        f"{self.host}:{self.root}/{item.remote_name}",
                    ]
                )
                if copied.returncode != 0:
                    raise RemoteStagingError("remote stage copy failed")
                size, sha256 = self.identities[item.remote_name]
                verify = self._python_command(
                    (
                        "p=pathlib.Path(sys.argv[1]);"
                        "assert p.is_file() and not p.is_symlink();"
                        "assert p.stat().st_size==int(sys.argv[2]);"
                        "assert hashlib.sha256(p.read_bytes()).hexdigest()==sys.argv[3]"
                    ),
                    f"{self.root}/{item.remote_name}",
                    str(size),
                    sha256,
                )
                verified = self._run([*self._ssh_prefix(), verify])
                if verified.returncode != 0:
                    raise RemoteStagingError("remote stage copy identity differs")
            self._check_local_identities()
            return self
        except BaseException:
            self.cleanup()
            raise

    def path(self, remote_name: str) -> str:
        if remote_name not in {item.remote_name for item in self.files}:
            raise RemoteStagingError("requested file is not part of remote stage")
        return f"{self.root}/{remote_name}"

    def cleanup(self) -> None:
        if self.cleanup_verified:
            return
        self._check_transport_identities()
        remote_command = self._python_command(
            (
                "import os; p=pathlib.Path(sys.argv[1]);"
                "assert str(p).startswith('/tmp/wspq-');"
                "present=os.path.lexists(p);owner=p/'.owner';"
                "assert not present or (p.is_dir() and not p.is_symlink() and owner.is_file() "
                "and not owner.is_symlink() and owner.read_text(encoding='ascii')==sys.argv[2]);"
                "import shutil; shutil.rmtree(p) if present else None;"
                "assert not os.path.lexists(p)"
            ),
            self.root,
            self.owner_token,
        )
        removed = self._run([*self._ssh_prefix(), remote_command])
        if removed.returncode != 0:
            raise RemoteStagingError("remote stage cleanup could not be verified")
        self.cleanup_verified = True

    def __exit__(self, exc_type: object, exc: object, traceback: object) -> Literal[False]:
        del exc_type, exc, traceback
        self.cleanup()
        return False


def find_scp(ssh: Path) -> Path:
    """Resolve scp alongside configured ssh, falling back to PATH discovery."""
    adjacent = ssh.with_name("scp")
    if adjacent.is_file():
        return adjacent
    discovered = shutil.which("scp")
    if discovered is None:
        raise RemoteStagingError("scp is unavailable")
    return Path(discovered)
